### ISSUE TITLE
Task naming conventions

### ISSUE THREAD

**Issue by dimitraz** [microlib/usermanager#16]
- Unique identifier to link name of task and associated branch

**Comment by marcotroisi** [comment]
I think we're doing that already?

**Comment by dimitraz** [comment]
@luigizuccarelli thinks it can be improved

**Comment by marcotroisi** [comment]
Ok. Tipically branches are named after the ticket/task number, plus a short description. So either: 

`3-implement-something-whatever`

or 

`usermanager-3-implement-something-whatever`

or we can use a short code (_USM_) for the usermanager

`USM-3-implement-something-whatever`

**Comment by luigizuccarelli** [comment]
Excellent - I like the USM-3-implement-something.... - do we have consensus ?

**Comment by marcotroisi** [comment]
I like that too.

**Comment by dimitraz** [comment]
Cool

**Comment by marcotroisi** [comment]
Ok, let's make sure we use branch names that follow the `USM-XX-` line from
now on then. Same applies for all the repositories we are going to create.
